from micro_llm.services.auth_service import AuthService as AuthService
from micro_llm.services.llm_service import LlmService as LlmService
from typing import Protocol

class CommandContext(Protocol):
    @property
    def auth_service(self) -> AuthService: ...
    @property
    def llm_service(self) -> LlmService: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...

def make_context(auth_service: AuthService, llm_service: LlmService) -> CommandContext: ...
