from python_utils.auth import Auth

class AuthService(Auth):
    def __init__(self, secret_key: str, public_key: str) -> None: ...
    def get_token_data(self, token: str) -> dict[str, str]: ...
    def validate_user(self, token: str) -> None: ...
